version: '3.8'

services:

  web:
    build:
        context: ./app
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydatabase"

  mongo:
    image: "mongo:latest"
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

volumes:
  db_data: